export const data = [
  {
    img: "1-expanding-cards.png",
    link: "/ExpandingCards",
    name: "Expanding Cards",
    folder: "ExpandingCards",
  },
  {
    img: "2-progress-steps.png",
    link: "/ProgressSteps",
    name: "Progress Steps",
    folder: "ProgressSteps",
  },
  {
    img: "3-rotating-navigation-animation.png",
    link: "/RotatingNavigationAnimation",
    name: "Rotating Navigation Animation",
    folder: "RotatingNavigationAnimation",
  },
  {
    img: "4-hidden-search-widget.png",
    link: "/HiddenSearchWidget",
    name: "Hidden Search Widget",
    folder: "HiddenSearchWidget",
  },
  {
    img: "5-blurry-loading.png",
    link: "/BlurryLoading",
    name: "Blurry Loading",
    folder: "BlurryLoading",
  },
  {
    img: "6-fb-reactions-animation.png",
    link: "/fb-reactions-animation",
    name: "Fb Reactions Animation",
    folder: "FbReactionsAnimation",
  },
  {
    img: "7-split-landing-page.png",
    link: "/SplitLandingPage",
    name: "Split Landing Page",
    folder: "SplitLandingPage",
  },
  {
    img: "8-form-wave.png",
    link: "/Form Wave",
    name: "Form Wave",
    folder: "FormWave",
  },
  {
    img: "9-sound-board.png",
    link: "/SoundBoard",
    name: "Sound Board",
    folder: "SoundBoard",
  },
  {
    img: "15-incrementing-counter.png",
    link: "/IncrementingCounter",
    name: "Incrementing Counter",
    folder: "IncrementingCounter",
  },
  {
    img: "16-i18.png",
    link: "/I18",
    name: "I18",
    folder: "I18",
  },
  {
    img: "18-background-slider.png",
    link: "/BackgroundSlider",
    name: "Background Slider",
    folder: "BackgroundSlider",
  },
  {
    img: "19-theme-clock.png",
    link: "/ThemeClock",
    name: "Theme Clock",
    folder: "ThemeClock",
  },
  {
    img: "45-netflix-mobile-navigation.png",
    link: "/NetflixMobileNavigation",
    name: "Netflix Mobile Navigation",
    folder: "NetflixMobileNavigation",
  },
  {
    img: "41-verify-account-ui.png",
    link: "/VerifyAccountUi",
    name: "Verify Account Ui",
    folder: "VerifyAccountUi",
  },
  {
    img: "26-double-vertical-slider.png",
    link: "/double-vertical-slider",
    name: "DoubleVerticalSlider",
    folder: "DoubleVerticalSlider",
  },
  {
    img: "28-github-profiles.png",
    link: "/github-profiles",
    name: "Github Profiles",
    folder: "GithubProfiles",
  },
  {
    img: "18-quiz.png",
    link: "/quiz",
    name: "Quiz",
    folder: "Quiz",
  },
];
